
set nocompatible

"Vundle bootstrap
if (! filereadable($HOME . '/.vim/bundle/Vundle.vim/.git/config') && confirm("Clone Vundle?", "Y\nn") == 1)
    exec '!git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'
    echo 'Now you can run ":PluginInstall" to install all the plugins.'
endif
source ~/.vim/bundle/vundle_config


set backspace=indent,eol,start

set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

autocmd BufRead,BufNewFile *.md set filetype=markdown
" TO DO: consider set lbr for text files too
autocmd FileType markdown set linebreak
autocmd FileType markdown inoremap ``` ```<CR>```<Esc>O

if has("gui_running")
	set guifont=UbuntuMono-Bold:h16
	set columns=140
	set hlsearch
	set linespace=2

	" Try to get rid of middle-click-to-paste
	nnoremap <MiddleMouse> <Nop>
	nnoremap <2-MiddleMouse> <Nop>
	nnoremap <3-MiddleMouse> <Nop>
	nnoremap <4-MiddleMouse> <Nop>

	inoremap <MiddleMouse> <Nop>
	inoremap <2-MiddleMouse> <Nop>
	inoremap <3-MiddleMouse> <Nop>
	inoremap <4-MiddleMouse> <Nop>
endif

set nolist
set listchars=eol:¶,tab:⇥\ ,space:·
highlight NonText guibg=NONE ctermbg=NONE
highlight SpecialKey guibg=NONE ctermbg=NONE
highlight Comment ctermfg=777 guifg=#aaaaaa

syntax on
set display=lastline
set ruler
set number relativenumber
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
set cursorline
set incsearch

if &t_Co > 128
    set termguicolors
endif
colorscheme solarized8_high
set background=dark

set splitbelow
set splitright

set scrolloff=5

map <Space> <Nop>
let mapleader = " "
nnoremap <Leader>h <C-w>h
" Add a <Leader>hh mapping to short-circut various git plugin mappings
nnoremap <Leader>hh <C-w>h
nnoremap <Leader>j <C-w>j
nnoremap <Leader>k <C-w>k
nnoremap <Leader>l <C-w>l
nnoremap <Leader>a GVgg
nnoremap <Leader>. :set invlist<CR>
nnoremap <Leader>s :w<CR>
nnoremap <Leader>q ZZ
nnoremap <Leader>Q ZZ
function ToggleDarkBackground()
	if &background == 'dark'
		set background=light
	elseif &background == 'light'
		set background=dark
	endif
endfunction
nnoremap <Leader>b :call ToggleDarkBackground()<CR>
nnoremap <silent> <Leader>nf :NERDTreeFind<CR>
nnoremap <silent> <Leader>nt :NERDTreeToggle<CR>

nnoremap <Space>= <Nop>
autocmd Filetype text,markdown nnoremap <Space>= vipJA.<Backspace><Esc>

"inoremap ii <Esc>
inoremap jk <Esc>
inoremap kj <Esc>
"inoremap ja <Esc>ja
inoremap jA <Esc>jA
inoremap jI <Esc>jI

vnoremap v <Esc>

set timeoutlen=2000

set shell=bash
set shellcmdflag=-ic

set mouse=a

" From here on is plugin config

let g:comfortable_motion_friction = 300.0

"let g:better_whitespace_enabled=0

if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.branch = '⎇ '
let g:airline_symbols.maxlinenr = ''

let delimitMate_expand_cr = 1

set updatetime=1000

let g:user_emmet_leader_key=','
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_mode='i'

source ~/.vim/coc_config

