
set nocompatible

"Vundle bootstrap
if (! filereadable($HOME . '/.vim/bundle/Vundle.vim/.git/config') && confirm("Clone Vundle?", "Y\nn") == 1)
    exec '!git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'
    echo 'Now you can run ":PluginInstall" to install all the plugins.'
endif
source ~/.vim/vundle_config


set backspace=indent,eol,start

set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

autocmd BufRead,BufNewFile *.md set filetype=markdown
" TO DO: consider set lbr for text files too
autocmd FileType markdown set linebreak
autocmd FileType markdown inoremap ``` ```<CR>```<Esc>O

autocmd BufRead,BufNewFile .myrc      set filetype=sh
autocmd BufRead,BufNewFile .myaliases set filetype=sh
autocmd BufRead,BufNewFile vundle_config set filetype=vim
autocmd BufRead,BufNewFile coc_config set filetype=vim

if has("gui_running")
    set guifont=UbuntuMono-Bold:h16
    set columns=140
    set hlsearch
    set linespace=2

    " Try to get rid of middle-click-to-paste
    nnoremap <MiddleMouse> <Nop>
    nnoremap <2-MiddleMouse> <Nop>
    nnoremap <3-MiddleMouse> <Nop>
    nnoremap <4-MiddleMouse> <Nop>

    inoremap <MiddleMouse> <Nop>
    inoremap <2-MiddleMouse> <Nop>
    inoremap <3-MiddleMouse> <Nop>
    inoremap <4-MiddleMouse> <Nop>
endif

set nolist
set listchars=eol:¶,tab:⇥\ ,space:·
highlight NonText guibg=NONE ctermbg=NONE
highlight SpecialKey guibg=NONE ctermbg=NONE
highlight Comment ctermfg=777 guifg=#aaaaaa

syntax on
set display=lastline
set nowrap
set ruler
set number relativenumber
set signcolumn=auto:9
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
set colorcolumn=80
set cursorline
set incsearch
set ignorecase
set smartcase

if &t_Co > 128
    set termguicolors
endif
colorscheme solarized8_high
set background=dark

set scrolloff=5

map <Space> <Nop>
let mapleader = " "
" Unmap and remap some gitgutter mappings so <Leader>h works
let g:gitgutter_map_keys = 0
nmap [c <Plug>(GitGutterPrevHunk)
nmap ]c <Plug>(GitGutterNextHunk)
nnoremap <Leader>h <C-w>h
nnoremap <Leader>j <C-w>j
nnoremap <Leader>k <C-w>k
nnoremap <Leader>l <C-w>l
nnoremap <Leader>a GVgg
nnoremap <Leader>. :set invlist<CR>
nnoremap <Leader>s :w<CR>
nnoremap <silent> <Leader>q :wqa<CR>
nnoremap <silent> <Leader>Q :qa!<CR>
nnoremap <silent> <Leader>w :confirm q<CR>
function ToggleDarkBackground()
    if &background == 'dark'
        set background=light
    elseif &background == 'light'
        set background=dark
    endif
endfunction
nnoremap <Leader>b :call ToggleDarkBackground()<CR>
nnoremap <silent> <Leader>nf :NERDTreeFind<CR>
nnoremap <silent> <Leader>nt :NERDTreeToggle<CR>

nnoremap <Space>= <Nop>
autocmd Filetype text,markdown nnoremap <Space>= vipJA.<Backspace><Esc>

autocmd Filetype java nnoremap <Leader>O :CocCommand java.action.organizeImports<CR>

set splitbelow
set splitright
nnoremap <Leader>- :split<CR>
nnoremap <Leader><Bslash> :vsplit<CR>

"inoremap ii <Esc>
inoremap jk <Esc>
inoremap kj <Esc>
"inoremap ja <Esc>ja
inoremap jA <Esc>jA
inoremap jI <Esc>jI

vnoremap v <Esc>

set timeoutlen=2000

if executable("zsh")
    set shell=zsh
else
    set shell=bash
endif
set shellcmdflag=-ic

set mouse=a

cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" From here on is plugin config

let g:comfortable_motion_friction = 200.0

"let g:better_whitespace_enabled=0


" Lots of airline config

let g:airline_skip_empty_sections = 1
let g:airline_inactive_collapse=0

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#show_splits = 1
let g:airline#extensions#tabline#tab_nr_type = 2
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_tab_count = 1
let g:airline#extensions#tabline#close_symbol = '✖︎'

let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.branch = '⎇ '
let g:airline_symbols.maxlinenr = ''

let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''

let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
" (end airline config)

let delimitMate_expand_cr = 2
let delimitMate_expand_space = 1

set updatetime=1000

let g:user_emmet_leader_key=','
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_mode='i'

let g:ft_improved_ignorecase = 1

let g:NERDTreeGitStatusIndicatorMapCustom = {
                \ 'Modified'  :'*',
                \ 'Staged'    :'✚',
                \ 'Untracked' :'✭',
                \ 'Renamed'   :'➜',
                \ 'Unmerged'  :'═',
                \ 'Deleted'   :'✖',
                \ 'Dirty'     :'✗',
                \ 'Ignored'   :'☒',
                \ 'Clean'     :'✔︎',
                \ 'Unknown'   :'?',
                \ }

" For fzf
nnoremap <silent> <C-p> :Files!<CR>

source ~/.vim/coc_config

